apiVersion: v1
kind: ConfigMap
metadata:
  name: taskmanager-config
  namespace: taskmanagerapp
data:
  application.properties: |
    spring.application.name=TaskManagerApp
    server.port=8083
    spring.data.mongodb.uri=mongodb://mongo-db.taskmanagerapp.svc.cluster.local:27017/taskmanagerdb
